### ISSUE TITLE
Error: No such command "configure".

### ISSUE THREAD

**Issue by jdpopkin** [jbaiter/zotero-cli#10]
I just installed from master today (via `pip install git+git://github.com/jbaiter/zotero-cli.git@master`). `zotcli configure` doesn't seem to work. 

```
$ zotcli configure
Usage: zotcli [OPTIONS] COMMAND [ARGS]...

Error: No such command "configure".```

**Comment by jbaiter** [comment]
Are you sure that your `zotcli` refers to the version installed with `pip`? What does `which zotcli` say?
I just installed with the exact pip line into a clean virtualenv and can run `zotcli configure` without any problems :/

**Comment by jdpopkin** [comment]
`which zotcli` says `/usr/local/bin/zotcli`.

I've never installed this program before as far as I'm aware, and all commands aside from `configure` seem to work.

**Comment by jdpopkin** [comment]
Oh, I see - based on bash history it looks like I had used `pip install zotero-cli` before `pip install git+git://github.com/jbaiter/zotero-cli.git@master`. `pip uninstall zotero-cli` followed by `pip install git+git://github.com/jbaiter/zotero-cli.git@master` solved the problem.

Sorry about that!
