### ISSUE TITLE
Pandoc permission error when adding a note to a zotero item

### ISSUE THREAD

**Issue by joelostblom** [jbaiter/zotero-cli#19]
I am receiving a pandoc permission error when adding noted to zotero. The note is still added correctly and all its content is there, so I am not sure where the error stems from. Here is the output from running `zotcli -v add-note <id>`

```python
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.zotero.org
DEBUG:requests.packages.urllib3.connectionpool:https://api.zotero.org:443 "GET /items/new?itemType=note HTTP/1.1" 200 82
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.zotero.org
DEBUG:requests.packages.urllib3.connectionpool:https://api.zotero.org:443 "GET /users/1905432/items?limit=1&format=json HTTP/1.1" 200 701
Found /home/joel/anaconda3/bin/pandoc, but not using it because of an error:
[Errno 13] Permission denied
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.zotero.org
DEBUG:requests.packages.urllib3.connectionpool:https://api.zotero.org:443 "POST /users/1905432/items HTTP/1.1" 200 564
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.zotero.org
DEBUG:requests.packages.urllib3.connectionpool:https://api.zotero.org:443 "PATCH /users/1905432/items/DRVZJ8MT HTTP/1.1" 204 0
```

The permissions of `/home/joel/anaconda3/bin/pandoc` are
```bash
-rwxrwxr-x 2 joel users 53173152 Nov 15 06:49 pandoc*
```

**Comment by jbaiter** [comment]
That's interesting, since the binary has execute permissions for all users... Can you run `/home/joel/anaconda3/bin/pandoc` as user `joel` from outside of Python?

**Comment by joelostblom** [comment]
II think this was an issue with the pandoc I was using locally. I changed it so that my distribution's pandoc binary comes before the one provided with anaconda on my PATH, and I haven't seen the problem since. Sorry, I forgot to update here.
