### ISSUE TITLE
Issue with configuring webdav 'Unknown error, please check your settings'

### ISSUE THREAD

**Issue by linktozelda** [jbaiter/zotero-cli#29]
Installed ZOTCLI with no problems using easy_install and pip on OSX. running `zotcli configure` seems to work well, until it gets to setting up my webdav: I input all the correct information for the server (url with http://, username, password) and I get "`Unknown error, please check your settings"`

Have confirmed and tested that my webdav server is working correctly and that I'm using the right username and password to access it. I've tried to find the .config file to have a look at settings but don't find it in `~/.config/zotcli/config.ini` Should I create the file, or is it hiding somewhere else since I'm in an OSX environment?

Any help would be greatly appreciated!

**Comment by linktozelda** [comment]
Further info: tried telling it to Use Local Zotero Storage and ended up with another error

Have tried running `zotcli configure` under sudo in both instances with same results
```
[0] Local Zotero storage
[1] Use Zotero file cloud
[2] Use WebDAV storage
How do you want to access files for reading? [1]: 0
Traceback (most recent call last):
  File "/usr/local/bin/zotcli", line 9, in <module>
    load_entry_point('zotero-cli==0.3.0', 'console_scripts', 'zotcli')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/zotero_cli/cli.py", line 91, in configure
    storage_dirs = tuple(find_storage_directories())
  File "/Library/Python/2.7/site-packages/zotero_cli/cli.py", line 44, in find_storage_directories
    for fpath in candidate_iter:
  File "/Library/Python/2.7/site-packages/pathlib.py", line 982, in iterdir
    for name in self._accessor.listdir(self):
  File "/Library/Python/2.7/site-packages/pathlib.py", line 346, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [Errno 2] No such file or directory: '/Users/username/.mozilla/firefox'
```

**Comment by jbaiter** [comment]
I just pushed a change that gives more information about the exact reason for the WebDAV failure, could you install from the Git repository and try again?
Also, your second issue should be fixed as well in the latest code.

**Comment by linktozelda** [comment]
Thanks for the fast response. I've uninstalled the previous version and installed the newest from the Git repository. 

When setting up Webdav, I get this: ```
Unknown error, please check your settings.
Server response code was: 200
```
When I input the webdav url, I should be using something like this, correct? `http://my.webdav.server` without a trailing slash, since it adds the `/zotero` automatically?
--
Just for testing purposes, I also tried configuring with my local Zotero storage directory, copy pasted the path and received `Directory does not exist!`

Thanks for the help!

**Comment by jbaiter** [comment]
> When I input the webdav url, I should be using something like this, correct?

Yup, that's correct :-) The error was a *really* stupid mistake on my end, sorry for that. I had not tested with other WebDAV hosts besides my own...

> Just for testing purposes, I also tried configuring with my local Zotero storage directory, copy pasted the path and received Directory does not exist!

This might be a stupid question, but does the directory exist on your disk?

**Comment by linktozelda** [comment]
Solved on both counts! My path to the dir had an error in it. 

Not to be annoying, but can you do anything about the query function? It seems to only search for the word within the title of items in the DB. Any way that it could also search author and/or fulltext?

**Comment by jbaiter** [comment]
> Not to be annoying, but can you do anything about the query function? It seems to only search for the word within the title of items in the DB. Any way that it could also search author and/or fulltext?

I'm afraid that fulltext is currently out of scope, since it would take a lot of space on the hard disk. Authors should already be searched, if they are not, could you please open another issue for this?
