### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by jbaiter** [jbaiter/zotero-cli#9]
Currently the application is Python 2.7 only, it would be highly desirable to make it work under Python 3, especially since it's now becoming the default version in a lot of distributions.

**Comment by DancingQuanta** [comment]
Great! The current click implemention doesn't work for python 3 very well, raising errors saying command not found.

**Comment by DancingQuanta** [comment]
Some useful information on how Click behaves under Python 3 http://click.pocoo.org/5/python3/
